" basic housekeeping, enable syntax fast scrolling, line numbers, etc.
syntax on
set modelines=0
set wrap
set ttyfast
set laststatus=2
set number

" call the vimrc plug file
if filereadable(expand("~/.vimrc.plug"))
	source ~/.vimrc.plug
endif

colorscheme wal
